version: 2
updates:
  - directory: /
    package-ecosystem: cargo
    schedule:
      interval: daily
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry*"
          - "tracing*"
          - "tonic"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
