name: Rust
on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: cache ~/.cargo
        uses: Swatinem/rust-cache@v2

      - name: rustup install
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: cargo clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: --all-targets --all-features

      - name: cargo fmt --check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --check --all

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: cache ~/.cargo
        uses: Swatinem/rust-cache@v2

      - name: rustup install
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable

      - name: Build
        run: cargo build --all-features

      - name: Test
        run: cargo test
